[project]
name = "wikisentry"
version = "0.1.0"
description = "Real-time ML platform for analyzing Wikipedia edit streams"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.5",
]
